// src/app/card/normalcard/normalcard.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-normalcard',
  templateUrl: './normalcard.component.html',
  styleUrls: ['./normalcard.component.css']
})
export class NormalcardComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="wrapper">
	<label for="card">卡号:</label>
	<input type="text" name="" id="card" value="" placeholder="请输入卡号" />
	<div class="input-bar"></div>
	<br />
	<label for="passw">密码:</label>
	<input type="password" name="" id="passw" value="" placeholder="请输入密码" />
	<div class="input-bar"></div>
	<button>查询</button>
</div>

// vuecli/src/components/normalcard.vue
<template>
	<section class="wrapper">
		<label for="card">卡号:</label>
		<input type="text" name="" id="card" value="" placeholder="请输入卡号" />
		<section class="input-bar"></section>
		<br />
		<label for="passw">密码:</label>
		<input type="password" name="" id="passw" value="" placeholder="请输入密码" />
		<section class="input-bar"></section>
		<button>查询</button>
	</section>
</template>

<script>
	export default {

	}
</script>

<style scoped="scoped">
	.wrapper {
		top: 30px;
		width: 94%;
		text-align: left;
	}
	
	.wrapper input {
		position: relative;
		display: inline-block;
		background-color: #FCFCFC;
		font-size: 14px;
		padding: 6px 12px;
		border: none;
	}
	
	label {
		margin: 0 10px;
		font-size: 14px;
		color: #333;
	}
	
	.input-bar {
		position: relative;
		height: 5px;
		top: -3px;
		border: solid #c4c4c4;
		border-width: 0 1px 1px 1px;
	}
	
	button {
		display: block;
		width: 163px;
		background-color: #fe8233;
		color: #fff;
		border: none;
		border-radius: 36px;
		margin: 45px auto;
		padding: 8px 12px;
		font-size: 15px;
	}
</style>
