// vuecli/src/components/comingSoon.vue
<template>
	<ul>
		<li v-for="film of films" class="np-items">
			<section class="film-img">
				<img :src="film.poster.origin" />
			</section>
			<section class="np-info">
				<section class="film-name">
					{{film.name}}
				</section>
				<section class="film-intro">
					{{film.intro}}
				</section>
				<section class="film-count">
					9月30日上映&nbsp;&nbsp;&nbsp;&nbsp;星期五
				</section>
			</section>
		</li>
	</ul>
</template>

<script>
	import axios from 'axios'
	export default {
		data: () => {
			return {
				films: null
			}
		},
		mounted() {
			axios.get('v4/api/film/coming-soon?page=1&count=7').then(reg => {
				this.films = reg.data.data.films;
				console.log(this.films)
			})
		}
	}
</script>

<style scoped="scoped">
	.np-items {
		height: 125px;
		padding: 20px 0px;
		border-bottom: 1px dotted rgb(201, 201, 201);
		text-align: left;
	}
	
	.film-img {
		height: 100%;
		width: 60px;
		position: relative;
		display: inline-block;
		overflow: hidden;
	}
	
	.film-img img {
		width: 100%;
		position: absolute;
	}
	
	.np-info {
		padding-left: 15px;
		display: inline-block;
		width: 75%;
		vertical-align: top;
	}
	
	.film-name {
		font-size: 16px;
		line-height: 32px;
		color: #000;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}
	
	.film-intro {
		height: 24px;
		line-height: 24px;
		color: #8e8e8e;
		font-size: 12px;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
		width: 100%;
		display: inline-block;
	}
	
	.film-count {
		line-height: 24px;
		color: #ffb375;
		font-size: 12px;
		font-weight: bold;
	}
	
	.film-grade {
		float: right;
		font-size: 16px;
		line-height: 32px;
		color: #fc7103;
	}
</style>

// src/app/video/coming-soon/coming-soon.component.ts
import { Component, OnInit } from '@angular/core';
import { Http } from '@angular/http';

@Component({
	selector: 'app-coming-soon',
	templateUrl: './coming-soon.component.html',
	styleUrls: ['./coming-soon.component.css']
})
export class ComingSoonComponent implements OnInit {
	films=[];
	constructor(private http:Http) {}

	ngOnInit() {
		this.http.get('/v4/api/film/coming-soon?page=1&count=7').toPromise().then(res=>{
			console.log(res.json());
			this.films=res.json().data.films;
		})
	}
}
<div *ngFor="let film of films" class="np-items" routerLink='/film/{{film.id}}'>
	<div class="film-img">
		<img [src]="film.poster.origin"/>
	</div>
	<div class="np-info">
		<div class="film-name">
			{{film.name}}
			<div class="film-grade">
				{{film.grade}}
			</div>
		</div>
		<div class="film-intro">
			{{film.intro}}
		</div>
		<div class="film-count">
			9月30日上映&nbsp;&nbsp;&nbsp;&nbsp;星期日
		</div>
	</div>
</div>
